language: php
services:
  - mysql
branches:
  only:
    - version1.0
env:
  MYSQL_ROOT_PASSWORD: root

before_install:
  - which sqld || echo "no mysql"
  - systemctl status mysql || echo "no status"
  - echo "[mysqld]"
  - sudo systemctl start mysql || echo "no start"

install:
  - composer require --dev php-coveralls/php-coveralls

before_script:
  - mysql -u root -e 'CREATE DATABASE testDB;'
  - mysql -u root -e "CREATE USER 'moodledude'@'localhost' IDENTIFIED BY 'password'";
  - mysql -u root -e "GRANT ALL ON testDB.* TO 'moodledude'@'localhost';"
  - mysql -u root -e "SHOW DATABASES"
  - mysql -u root -e "USE testDB;CREATE TABLE ams_emulators(id int NOT NULL AUTO_INCREMENT,emulator_id varchar(100) DEFAULT NULL,state varchar(100) DEFAULT NULL,in_use varchar(10) DEFAULT NULL,PRIMARY KEY (id));"
  - mysql -u root -e "USE testDB;DESC ams_emulators"
  - mysql -u root -e "USE testDB;INSERT INTO ams_emulators(emulator_id, state, in_use) VALUES ('WCYC4C18809001072','device','false'),('ZBYA4C14405981207','device','true');"
  - mkdir -p build/logs
  - curl -s https://getcomposer.org/installer | php
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source --dev

script:
  - vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_success:
  - travis_retry php vendor/bin/php-coveralls
  - travis_retry php vendor/bin/php-coveralls -v
